-- =============================================================================
-- Benna Projects Manager – Enterprise-Grade Cryptographic Ledger Schema
-- Version 4.0  |  2026-06-08
-- Run this script in your Supabase SQL Editor.
-- =============================================================================

-- Enable required cryptographic and UUID extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- CRYPTOGRAPHIC IMMUTABLE AUDIT LEDGER
-- Keeps database tables "honest" by chaining records chronologically.
-- Each change records the row SHA-256 hash linked to the previous block hash.
-- =============================================================================

CREATE TABLE IF NOT EXISTS cryptographic_ledger (
    sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      TEXT NOT NULL,
    record_id       TEXT NOT NULL,
    action          TEXT NOT NULL,
    payload         JSONB NOT NULL,
    record_hash     TEXT NOT NULL,
    previous_hash   TEXT NOT NULL,
    block_hash      TEXT NOT NULL,
    timestamp       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ledger_table_record ON cryptographic_ledger(table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_ledger_timestamp    ON cryptographic_ledger(timestamp DESC);

-- Trigger function to build the cryptographic hash chain
CREATE OR REPLACE FUNCTION audit_to_ledger()
RETURNS TRIGGER AS $$
DECLARE
    prev_hash  TEXT;
    rec_json   JSONB;
    rec_hash   TEXT;
    bl_hash    TEXT;
    rec_id_val TEXT;
BEGIN
    -- Determine action and read payload
    IF (TG_OP = 'DELETE') THEN
        rec_json := to_jsonb(OLD);
    ELSE
        rec_json := to_jsonb(NEW);
    END IF;

    -- Dynamically extract primary key (id, key, or unknown)
    BEGIN
        IF (TG_OP = 'DELETE') THEN
            rec_id_val := OLD.id::text;
        ELSE
            rec_id_val := NEW.id::text;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        BEGIN
            IF (TG_OP = 'DELETE') THEN
                rec_id_val := OLD.key::text;
            ELSE
                rec_id_val := NEW.key::text;
            END IF;
        EXCEPTION WHEN OTHERS THEN
            rec_id_val := 'unknown';
        END;
    END;

    -- Retrieve block_hash of the last ledger block to chain
    SELECT block_hash INTO prev_hash 
    FROM cryptographic_ledger 
    ORDER BY sequence_number DESC 
    LIMIT 1;

    -- Genesis block hash fallback if empty
    IF prev_hash IS NULL THEN
        prev_hash := '0000000000000000000000000000000000000000000000000000000000000000';
    END IF;

    -- Hash of the payload
    rec_hash := encode(digest(rec_json::text, 'sha256'), 'hex');

    -- Link block_hash = SHA256(current_hash + previous_hash)
    bl_hash := encode(digest(rec_hash || prev_hash, 'sha256'), 'hex');

    -- Insert cryptographic record
    INSERT INTO cryptographic_ledger (
        table_name, record_id, action, payload, record_hash, previous_hash, block_hash
    ) VALUES (
        TG_TABLE_NAME, rec_id_val, TG_OP, rec_json, rec_hash, prev_hash, bl_hash
    );

    IF (TG_OP = 'DELETE') THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- HELPER FUNCTION: auto-update sync_updated_at
-- =============================================================================
CREATE OR REPLACE FUNCTION update_sync_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.sync_updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- 1. USERS
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               TEXT UNIQUE NOT NULL,
    password            TEXT NOT NULL,
    name                TEXT NOT NULL DEFAULT '',
    role                TEXT NOT NULL DEFAULT 'user'
                            CHECK (role IN ('admin', 'audit_manager', 'user')),
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status         TEXT DEFAULT 'synced',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT
);

CREATE TRIGGER trg_users_sync
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_users_ledger
    AFTER INSERT OR UPDATE OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 2. CATEGORIES
-- =============================================================================
CREATE TABLE IF NOT EXISTS categories (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name_en         TEXT NOT NULL,
    name_fr         TEXT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE TRIGGER trg_categories_sync
    BEFORE UPDATE ON categories
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_categories_ledger
    AFTER INSERT OR UPDATE OR DELETE ON categories
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 3. SUPPLIERS
-- =============================================================================
CREATE TABLE IF NOT EXISTS suppliers (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            TEXT NOT NULL,
    contact         TEXT,
    phone           TEXT,
    email           TEXT,
    address         TEXT,
    status          TEXT DEFAULT 'active',
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE TRIGGER trg_suppliers_sync
    BEFORE UPDATE ON suppliers
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_suppliers_ledger
    AFTER INSERT OR UPDATE OR DELETE ON suppliers
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 4. INVENTORY
-- =============================================================================
CREATE TABLE IF NOT EXISTS inventory (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            TEXT NOT NULL,
    category        TEXT NOT NULL DEFAULT 'General',
    category_id     UUID REFERENCES categories(id) ON DELETE SET NULL,
    quantity        INT NOT NULL DEFAULT 0,
    unit_price      NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    supplier        TEXT,
    location        TEXT NOT NULL DEFAULT 'Main Store',
    min_stock       INT DEFAULT 10,
    max_stock       INT DEFAULT 100,
    last_updated    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE INDEX IF NOT EXISTS idx_inventory_category_id ON inventory(category_id);

CREATE TRIGGER trg_inventory_sync
    BEFORE UPDATE ON inventory
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_inventory_ledger
    AFTER INSERT OR UPDATE OR DELETE ON inventory
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 5. TRUCKS
-- =============================================================================
CREATE TABLE IF NOT EXISTS trucks (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    plate_number            TEXT UNIQUE NOT NULL,
    model                   TEXT,
    capacity                NUMERIC(10, 2),
    status                  TEXT DEFAULT 'active'
                                CHECK (status IN ('active', 'maintenance', 'inactive')),
    latitude                NUMERIC(10, 7),
    longitude               NUMERIC(10, 7),
    last_location_update    TIMESTAMP WITH TIME ZONE,
    sync_status             TEXT DEFAULT 'synced',
    sync_updated_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived             BOOLEAN DEFAULT FALSE,
    _sync_error             TEXT
);

CREATE TRIGGER trg_trucks_sync
    BEFORE UPDATE ON trucks
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_trucks_ledger
    AFTER INSERT OR UPDATE OR DELETE ON trucks
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 6. AUDIT LOGS
-- =============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action          TEXT NOT NULL,
    table_name      TEXT NOT NULL,
    record_id       TEXT NOT NULL,
    old_values      TEXT,
    new_values      TEXT,
    ip_address      TEXT,
    timestamp       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE TRIGGER trg_audit_logs_sync
    BEFORE UPDATE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

-- =============================================================================
-- 7. USAGE LOGS
-- =============================================================================
CREATE TABLE IF NOT EXISTS usage_logs (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    inventory_item_id   UUID REFERENCES inventory(id) ON DELETE CASCADE,
    item_name           TEXT NOT NULL,
    quantity_changed    INT NOT NULL,
    previous_quantity   INT NOT NULL,
    new_quantity        INT NOT NULL,
    user_id             BIGINT REFERENCES users(id) ON DELETE SET NULL,
    authorized_by_name  TEXT,
    authorized_by_title TEXT,
    truck_id            UUID REFERENCES trucks(id) ON DELETE SET NULL,
    transaction_type    TEXT DEFAULT 'OUT',
    timestamp           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status         TEXT DEFAULT 'synced',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT
);

CREATE INDEX IF NOT EXISTS idx_usage_logs_inventory_item_id ON usage_logs(inventory_item_id);

CREATE TRIGGER trg_usage_logs_sync
    BEFORE UPDATE ON usage_logs
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_usage_logs_ledger
    AFTER INSERT OR UPDATE OR DELETE ON usage_logs
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 8. ORDERS
-- =============================================================================
CREATE TABLE IF NOT EXISTS orders (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    supplier_id             UUID REFERENCES suppliers(id) ON DELETE RESTRICT,
    order_date              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expected_date           DATE,
    total_amount            NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    paid_amount             NUMERIC(15, 2) DEFAULT 0.00,
    status                  TEXT DEFAULT 'pending'
                                CHECK (status IN ('pending', 'partial', 'paid', 'cancelled')),
    delivery_status         TEXT DEFAULT 'pending',
    actual_delivery_date    DATE,
    notes                   TEXT,
    created_by              TEXT,
    created_at              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status             TEXT DEFAULT 'synced',
    sync_updated_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived             BOOLEAN DEFAULT FALSE,
    _sync_error             TEXT
);

CREATE TRIGGER trg_orders_sync
    BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_orders_ledger
    AFTER INSERT OR UPDATE OR DELETE ON orders
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 9. ORDER ITEMS
-- =============================================================================
CREATE TABLE IF NOT EXISTS order_items (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id            UUID REFERENCES orders(id) ON DELETE CASCADE,
    inventory_item_id   UUID REFERENCES inventory(id) ON DELETE SET NULL,
    description         TEXT,
    quantity            INT NOT NULL CHECK (quantity > 0),
    delivered_quantity  INT DEFAULT 0,
    unit_price          NUMERIC(15, 2) NOT NULL CHECK (unit_price >= 0),
    total               NUMERIC(15, 2) NOT NULL,
    sync_status         TEXT DEFAULT 'synced',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

CREATE TRIGGER trg_order_items_sync
    BEFORE UPDATE ON order_items
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_order_items_ledger
    AFTER INSERT OR UPDATE OR DELETE ON order_items
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 10. PAYMENTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS payments (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID REFERENCES orders(id) ON DELETE CASCADE,
    amount          NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    payment_date    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    method          TEXT DEFAULT 'cash'
                        CHECK (method IN ('cash', 'bank', 'check', 'credit', 'other')),
    reference       TEXT,
    notes           TEXT,
    created_by      TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);

CREATE TRIGGER trg_payments_sync
    BEFORE UPDATE ON payments
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_payments_ledger
    AFTER INSERT OR UPDATE OR DELETE ON payments
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 11. ACCOUNTS (Chart of Accounts)
-- =============================================================================
CREATE TABLE IF NOT EXISTS accounts (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    type            TEXT NOT NULL
                        CHECK (type IN ('asset', 'liability', 'equity', 'revenue', 'expense')),
    balance         NUMERIC(15, 2) DEFAULT 0.00,
    currency        TEXT DEFAULT 'XAF',
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE TRIGGER trg_accounts_sync
    BEFORE UPDATE ON accounts
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_accounts_ledger
    AFTER INSERT OR UPDATE OR DELETE ON accounts
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 12. INVOICES
-- =============================================================================
CREATE TABLE IF NOT EXISTS invoices (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_id       TEXT NOT NULL,
    order_id        UUID REFERENCES orders(id) ON DELETE SET NULL,
    invoice_date    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    due_date        TIMESTAMP WITH TIME ZONE,
    total_amount    NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    paid_amount     NUMERIC(15, 2) DEFAULT 0.00,
    status          TEXT DEFAULT 'draft'
                        CHECK (status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled')),
    notes           TEXT,
    created_by      TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE INDEX IF NOT EXISTS idx_invoices_order_id ON invoices(order_id);

CREATE TRIGGER trg_invoices_sync
    BEFORE UPDATE ON invoices
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_invoices_ledger
    AFTER INSERT OR UPDATE OR DELETE ON invoices
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 13. TRANSACTIONS (Ledger)
-- =============================================================================
CREATE TABLE IF NOT EXISTS transactions (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id          TEXT REFERENCES accounts(id) ON DELETE RESTRICT,
    invoice_id          UUID REFERENCES invoices(id) ON DELETE SET NULL,
    amount              NUMERIC(15, 2) NOT NULL,
    type                TEXT NOT NULL CHECK (type IN ('credit', 'debit')),
    transaction_date    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    description         TEXT,
    reference           TEXT,
    created_by          TEXT,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status         TEXT DEFAULT 'synced',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT
);

CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_invoice_id ON transactions(invoice_id);

CREATE TRIGGER trg_transactions_sync
    BEFORE UPDATE ON transactions
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_transactions_ledger
    AFTER INSERT OR UPDATE OR DELETE ON transactions
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 14. GRANITE DELIVERIES
-- =============================================================================
CREATE TABLE IF NOT EXISTS granite_deliveries (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date            DATE NOT NULL DEFAULT CURRENT_DATE,
    truck_id        UUID REFERENCES trucks(id) ON DELETE RESTRICT,
    driver_name     TEXT NOT NULL,
    granite_type    TEXT NOT NULL,
    empty_weight    NUMERIC(10, 2),
    loaded_weight   NUMERIC(10, 2),
    net_weight      NUMERIC(10, 2),
    volume_m3       NUMERIC(10, 2),
    quantity        NUMERIC(10, 2) NOT NULL,
    unit_price      NUMERIC(15, 2) NOT NULL,
    total_amount    NUMERIC(15, 2) NOT NULL,
    client_name     TEXT,
    status          TEXT DEFAULT 'delivered'
                        CHECK (status IN ('pending', 'delivered', 'cancelled')),
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE INDEX IF NOT EXISTS idx_granite_deliveries_truck_id ON granite_deliveries(truck_id);

CREATE TRIGGER trg_granite_deliveries_sync
    BEFORE UPDATE ON granite_deliveries
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_granite_deliveries_ledger
    AFTER INSERT OR UPDATE OR DELETE ON granite_deliveries
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 15. NOTIFICATIONS
-- =============================================================================
CREATE TABLE IF NOT EXISTS notifications (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    message         TEXT NOT NULL,
    type            TEXT NOT NULL,
    is_read         BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE TRIGGER trg_notifications_sync
    BEFORE UPDATE ON notifications
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

-- =============================================================================
-- 16. EMPLOYEES
-- =============================================================================
CREATE TABLE IF NOT EXISTS employees (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name                TEXT NOT NULL,
    email               TEXT,
    phone               TEXT,
    role                TEXT NOT NULL DEFAULT 'Staff',
    department          TEXT NOT NULL DEFAULT 'General',
    salary              NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    hire_date           DATE NOT NULL DEFAULT CURRENT_DATE,
    status              TEXT DEFAULT 'active'
                            CHECK (status IN ('active', 'inactive', 'on_leave')),
    performance_notes   TEXT,
    resume_text         TEXT,
    device_enroll_id    TEXT UNIQUE,
    supervisor_id       BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status         TEXT DEFAULT 'synced',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT
);

CREATE TRIGGER trg_employees_sync
    BEFORE UPDATE ON employees
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_employees_ledger
    AFTER INSERT OR UPDATE OR DELETE ON employees
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 17. APPLICANTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS applicants (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name                TEXT NOT NULL,
    email               TEXT NOT NULL,
    phone               TEXT,
    role_applied        TEXT NOT NULL,
    experience_years    INT NOT NULL DEFAULT 0,
    skills              TEXT,
    resume_text         TEXT,
    ai_score            NUMERIC(5, 2) DEFAULT 0.00,
    ai_assessment       TEXT,
    status              TEXT DEFAULT 'pending'
                            CHECK (status IN ('pending', 'reviewed', 'interviewed', 'accepted', 'rejected')),
    applied_date        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status         TEXT DEFAULT 'synced',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT
);

CREATE TRIGGER trg_applicants_sync
    BEFORE UPDATE ON applicants
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_applicants_ledger
    AFTER INSERT OR UPDATE OR DELETE ON applicants
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 18. ATTENDANCE
-- =============================================================================
CREATE TABLE IF NOT EXISTS attendance (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id         UUID REFERENCES employees(id) ON DELETE SET NULL,
    device_enroll_id    TEXT NOT NULL,
    timestamp           TIMESTAMP WITH TIME ZONE NOT NULL,
    verification_method TEXT DEFAULT 'unknown'
                            CHECK (verification_method IN
                                ('face', 'fingerprint', 'card', 'password', 'manual', 'unknown')),
    direction           TEXT DEFAULT 'unknown'
                            CHECK (direction IN ('in', 'out', 'break_in', 'break_out', 'unknown')),
    source              TEXT DEFAULT 'online_push'
                            CHECK (source IN ('online_push', 'usb_import', 'manual_entry')),
    device_sn           TEXT,
    sync_status         TEXT DEFAULT 'pending',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT,
    UNIQUE (device_enroll_id, timestamp)
);

CREATE INDEX IF NOT EXISTS idx_attendance_employee_id ON attendance(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_timestamp    ON attendance(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_device_sn    ON attendance(device_sn);

CREATE TRIGGER trg_attendance_sync
    BEFORE UPDATE ON attendance
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_attendance_ledger
    AFTER INSERT OR UPDATE OR DELETE ON attendance
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 19. EMPLOYEE TASKS
-- =============================================================================
CREATE TABLE IF NOT EXISTS employee_tasks (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id     UUID REFERENCES employees(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    description     TEXT,
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'in_progress', 'completed')),
    due_date        DATE,
    assigned_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status     TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived     BOOLEAN DEFAULT FALSE,
    _sync_error     TEXT
);

CREATE INDEX IF NOT EXISTS idx_employee_tasks_employee_id ON employee_tasks(employee_id);

CREATE TRIGGER trg_employee_tasks_sync
    BEFORE UPDATE ON employee_tasks
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_employee_tasks_ledger
    AFTER INSERT OR UPDATE OR DELETE ON employee_tasks
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 20. EMPLOYEE PERFORMANCE
-- =============================================================================
CREATE TABLE IF NOT EXISTS employee_performance (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id         UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    month               TEXT NOT NULL,
    task_score          INT NOT NULL DEFAULT 0,
    boss_review_score   INT NOT NULL DEFAULT 0,
    boss_commentary     TEXT,
    attendance_score    INT NOT NULL DEFAULT 0,
    peer_feedback_score INT NOT NULL DEFAULT 0,
    skill_dev_score     INT NOT NULL DEFAULT 0,
    overtime_score      INT NOT NULL DEFAULT 0,
    composite_score     INT GENERATED ALWAYS AS (
        (task_score + boss_review_score + attendance_score +
         peer_feedback_score + skill_dev_score + overtime_score) / 6
    ) STORED,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status         TEXT DEFAULT 'synced',
    sync_updated_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived         BOOLEAN DEFAULT FALSE,
    _sync_error         TEXT,
    UNIQUE (employee_id, month)
);

CREATE INDEX IF NOT EXISTS idx_employee_performance_employee_id ON employee_performance(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_performance_month       ON employee_performance(month);

CREATE TRIGGER trg_employee_performance_sync
    BEFORE UPDATE ON employee_performance
    FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

CREATE TRIGGER trg_employee_performance_ledger
    AFTER INSERT OR UPDATE OR DELETE ON employee_performance
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 21. AI INSIGHTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS ai_insights (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role        TEXT NOT NULL CHECK (role IN ('user', 'agent')),
    content     TEXT NOT NULL,
    metadata    TEXT,
    timestamp   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 22. SETTINGS
-- =============================================================================
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT
);

CREATE TRIGGER trg_settings_ledger
    AFTER INSERT OR UPDATE OR DELETE ON settings
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- 23. APP CONFIG
-- =============================================================================
CREATE TABLE IF NOT EXISTS app_config (
    key        TEXT PRIMARY KEY,
    value      TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_app_config_ledger
    AFTER INSERT OR UPDATE OR DELETE ON app_config
    FOR EACH ROW EXECUTE FUNCTION audit_to_ledger();

-- =============================================================================
-- DISABLE ROW LEVEL SECURITY (bypass and execute via Supabase Client Service Role)
-- =============================================================================
ALTER TABLE users                 DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories            DISABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers             DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory             DISABLE ROW LEVEL SECURITY;
ALTER TABLE trucks                DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs            DISABLE ROW LEVEL SECURITY;
ALTER TABLE usage_logs            DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders                DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items           DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments              DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts              DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices              DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions          DISABLE ROW LEVEL SECURITY;
ALTER TABLE granite_deliveries    DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications         DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees             DISABLE ROW LEVEL SECURITY;
ALTER TABLE applicants            DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance            DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_tasks        DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_performance  DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights           DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings              DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_config            DISABLE ROW LEVEL SECURITY;
ALTER TABLE cryptographic_ledger  DISABLE ROW LEVEL SECURITY;

-- =============================================================================
-- SEED DEFAULT CONFIGS
-- =============================================================================
INSERT INTO app_config (key, value) VALUES
    ('attendance_device_ip',   '192.168.0.100'),
    ('attendance_device_port', '5005'),
    ('attendance_server_ip',   '192.168.1.200'),
    ('attendance_server_port', '7005'),
    ('attendance_use_server',  'false'),
    ('currency',               'XAF'),
    ('company_name',           'Benna Projects')
ON CONFLICT (key) DO NOTHING;

-- =============================================================================
-- END OF SCHEMA
-- =============================================================================
