-- Supabase Database Schema for Benna Stock Manager
-- This script covers all tables, columns, constraints, foreign keys, indexes, and triggers to ensure complete sync capability.

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Clean up existing tables if needed (uncomment if you want a fresh start)
-- DROP TABLE IF EXISTS ai_insights CASCADE;
-- DROP TABLE IF EXISTS attendance CASCADE;
-- DROP TABLE IF EXISTS applicants CASCADE;
-- DROP TABLE IF EXISTS employees CASCADE;
-- DROP TABLE IF EXISTS notifications CASCADE;
-- DROP TABLE IF EXISTS granite_deliveries CASCADE;
-- DROP TABLE IF EXISTS trucks CASCADE;
-- DROP TABLE IF EXISTS transactions CASCADE;
-- DROP TABLE IF EXISTS invoices CASCADE;
-- DROP TABLE IF EXISTS accounts CASCADE;
-- DROP TABLE IF EXISTS payments CASCADE;
-- DROP TABLE IF EXISTS order_items CASCADE;
-- DROP TABLE IF EXISTS orders CASCADE;
-- DROP TABLE IF EXISTS suppliers CASCADE;
-- DROP TABLE IF EXISTS categories CASCADE;
-- DROP TABLE IF EXISTS usage_logs CASCADE;
-- DROP TABLE IF EXISTS audit_logs CASCADE;
-- DROP TABLE IF EXISTS inventory CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;
-- DROP TABLE IF EXISTS settings CASCADE;
-- DROP TABLE IF EXISTS app_config CASCADE;

---------------------------------------------------------
-- 1. USERS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin', 'audit_manager', 'user')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 2. CATEGORIES
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name_en TEXT NOT NULL,
    name_fr TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 3. SUPPLIERS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    contact TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 4. INVENTORY
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
    quantity INT NOT NULL DEFAULT 0,
    unit_price NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    supplier TEXT,
    location TEXT NOT NULL DEFAULT 'Main Store',
    min_stock INT DEFAULT 10,
    max_stock INT DEFAULT 100,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 5. TRUCKS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS trucks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    plate_number TEXT UNIQUE NOT NULL,
    model TEXT,
    capacity NUMERIC(10, 2),
    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'maintenance', 'inactive')),
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    last_location_update TEXT,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 6. AUDIT LOGS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL,
    old_values TEXT,
    new_values TEXT,
    ip_address TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 7. USAGE LOGS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS usage_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    inventory_item_id UUID REFERENCES inventory(id) ON DELETE CASCADE,
    item_name TEXT NOT NULL,
    quantity_changed INT NOT NULL,
    previous_quantity INT NOT NULL,
    new_quantity INT NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    authorized_by_name TEXT,
    authorized_by_title TEXT,
    truck_id UUID REFERENCES trucks(id) ON DELETE SET NULL,
    transaction_type TEXT DEFAULT 'OUT',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 8. ORDERS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    supplier_id UUID REFERENCES suppliers(id) ON DELETE RESTRICT,
    order_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expected_date DATE,
    total_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    paid_amount NUMERIC(15, 2) DEFAULT 0.00,
    status TEXT CHECK(status IN ('pending', 'partial', 'paid', 'cancelled')) DEFAULT 'pending',
    delivery_status TEXT DEFAULT 'pending',
    actual_delivery_date DATE,
    notes TEXT,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 9. ORDER ITEMS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    inventory_item_id UUID REFERENCES inventory(id) ON DELETE SET NULL,
    description TEXT,
    quantity INT NOT NULL CHECK(quantity > 0),
    delivered_quantity INT DEFAULT 0,
    unit_price NUMERIC(15, 2) NOT NULL CHECK(unit_price >= 0),
    total NUMERIC(15, 2) NOT NULL,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 10. PAYMENTS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    amount NUMERIC(15, 2) NOT NULL CHECK(amount > 0),
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    method TEXT CHECK(method IN ('cash', 'bank', 'check', 'credit', 'other')) DEFAULT 'cash',
    reference TEXT,
    notes TEXT,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 11. ACCOUNTS (Chart of Accounts)
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY, -- often numeric code like '1010' or UUID
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('asset', 'liability', 'equity', 'revenue', 'expense')),
    balance NUMERIC(15, 2) DEFAULT 0.00,
    currency TEXT DEFAULT 'USD',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 12. INVOICES
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_id TEXT NOT NULL, -- or UUID references if clients table is added later
    order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
    invoice_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP WITH TIME ZONE,
    total_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    paid_amount NUMERIC(15, 2) DEFAULT 0.00,
    status TEXT CHECK(status IN ('draft', 'sent', 'paid', 'overdue', 'cancelled')) DEFAULT 'draft',
    notes TEXT,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 13. TRANSACTIONS (Ledger Transactions)
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    account_id TEXT REFERENCES accounts(id) ON DELETE RESTRICT,
    invoice_id UUID REFERENCES invoices(id) ON DELETE SET NULL,
    amount NUMERIC(15, 2) NOT NULL,
    type TEXT CHECK(type IN ('credit', 'debit')) NOT NULL,
    transaction_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    description TEXT,
    reference TEXT,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 14. GRANITE DELIVERIES
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS granite_deliveries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date TEXT NOT NULL,
    truck_id UUID REFERENCES trucks(id) ON DELETE RESTRICT,
    driver_name TEXT NOT NULL,
    granite_type TEXT NOT NULL,
    empty_weight NUMERIC(10, 2),
    loaded_weight NUMERIC(10, 2),
    net_weight NUMERIC(10, 2),
    volume_m3 NUMERIC(10, 2),
    quantity NUMERIC(10, 2) NOT NULL,
    unit_price NUMERIC(15, 2) NOT NULL,
    total_amount NUMERIC(15, 2) NOT NULL,
    client_name TEXT,
    status TEXT DEFAULT 'delivered' CHECK(status IN ('pending', 'delivered', 'cancelled')),
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 15. NOTIFICATIONS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    message TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN DEFAULT FALSE,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 16. EMPLOYEES
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS employees (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    role TEXT NOT NULL,
    department TEXT NOT NULL,
    salary NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    hire_date TEXT NOT NULL,
    status TEXT CHECK(status IN ('active', 'inactive', 'on_leave')) DEFAULT 'active',
    performance_notes TEXT,
    resume_text TEXT,
    device_enroll_id TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 17. APPLICANTS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS applicants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    role_applied TEXT NOT NULL,
    experience_years INT NOT NULL DEFAULT 0,
    skills TEXT,
    resume_text TEXT,
    ai_score NUMERIC(5, 2) DEFAULT 0.00,
    ai_assessment TEXT,
    status TEXT CHECK(status IN ('pending', 'reviewed', 'interviewed', 'accepted', 'rejected')) DEFAULT 'pending',
    applied_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_status TEXT DEFAULT 'synced',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 18. ATTENDANCE
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID REFERENCES employees(id) ON DELETE SET NULL,
    device_enroll_id TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    verification_method TEXT CHECK(verification_method IN ('face', 'fingerprint', 'card', 'password', 'manual', 'unknown')),
    direction TEXT CHECK(direction IN ('in', 'out', 'break_in', 'break_out', 'unknown')) DEFAULT 'unknown',
    source TEXT CHECK(source IN ('online_push', 'usb_import', 'manual_entry')) DEFAULT 'online_push',
    sync_status TEXT DEFAULT 'pending',
    sync_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_archived BOOLEAN DEFAULT FALSE,
    _sync_error TEXT
);

---------------------------------------------------------
-- 19. AI INSIGHTS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role TEXT NOT NULL CHECK(role IN ('user', 'agent')),
    content TEXT NOT NULL,
    metadata TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------
-- 20. SETTINGS
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

---------------------------------------------------------
-- 21. APP CONFIG
---------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_config (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------
-- AUTOMATIC TIMESTAMPS TRIGGERS & FUNCTIONS
---------------------------------------------------------

-- Create a helper function to update updated_at / sync_updated_at automatically
CREATE OR REPLACE FUNCTION update_sync_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.sync_updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers to tables that have sync_updated_at
CREATE TRIGGER trigger_update_users_sync_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_categories_sync_updated_at BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_suppliers_sync_updated_at BEFORE UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_inventory_sync_updated_at BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_trucks_sync_updated_at BEFORE UPDATE ON trucks FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_audit_logs_sync_updated_at BEFORE UPDATE ON audit_logs FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_usage_logs_sync_updated_at BEFORE UPDATE ON usage_logs FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_orders_sync_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_order_items_sync_updated_at BEFORE UPDATE ON order_items FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_payments_sync_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_accounts_sync_updated_at BEFORE UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_invoices_sync_updated_at BEFORE UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_transactions_sync_updated_at BEFORE UPDATE ON transactions FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_granite_deliveries_sync_updated_at BEFORE UPDATE ON granite_deliveries FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_notifications_sync_updated_at BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_employees_sync_updated_at BEFORE UPDATE ON employees FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_applicants_sync_updated_at BEFORE UPDATE ON applicants FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();
CREATE TRIGGER trigger_update_attendance_sync_updated_at BEFORE UPDATE ON attendance FOR EACH ROW EXECUTE FUNCTION update_sync_timestamp();

---------------------------------------------------------
-- INDEXES FOR PERFORMANCE
---------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_inventory_category_id ON inventory(category_id);
CREATE INDEX IF NOT EXISTS idx_usage_logs_inventory_item_id ON usage_logs(inventory_item_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_invoice_id ON transactions(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoices_order_id ON invoices(order_id);
CREATE INDEX IF NOT EXISTS idx_attendance_employee_id ON attendance(employee_id);
CREATE INDEX IF NOT EXISTS idx_granite_deliveries_truck_id ON granite_deliveries(truck_id);

-- Disable Row Level Security (RLS) on all tables for easy central sync integration,
-- or alternatively setup RLS policy allow-all (uncomment as needed).
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE trucks DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE usage_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE granite_deliveries DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE applicants DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_insights DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_config DISABLE ROW LEVEL SECURITY;
