import jsPDF from 'jspdf';
import i18n from '../i18n';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from './currency';
import { numberToWords } from './numberToWords';

interface OrderItem {
  description: string;
  quantity: number;
  unit_price: number;
  total: number;
}

interface OrderData {
  id: string;
  order_date: string;
  supplier: {
    name: string;
    address?: string;
    phone?: string;
    email?: string;
  } | null;
  items: OrderItem[];
  total_amount: number;
  paid_amount: number;
  balance: number;
}

interface Settings {
  company_logo?: string;
}

const LEFT_MARGIN = 20;

export const generateOrderPDF = (order: OrderData, settings: Settings, t: (key: string) => string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Add Logo
  if (settings.company_logo) {
    try {
      doc.addImage(settings.company_logo, 'PNG', LEFT_MARGIN, 15, 30, 30);
    } catch (e) {
      console.error('Error adding logo to PDF:', e);
    }
  }

  // Header
  doc.setFontSize(20);
  doc.setTextColor(0, 31, 63); // Navy Blue (#001f3f)
  doc.text(t('purchase_order'), pageWidth - 15, 25, { align: 'right' });

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`${t('order_number')}: ${order.id.substring(0, 8)}`, pageWidth - 15, 32, { align: 'right' });
  doc.text(`${t('order_date')}: ${new Date(order.order_date).toLocaleDateString()}`, pageWidth - 15, 37, { align: 'right' });

  // Supplier Info
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(t('supplier'), LEFT_MARGIN, 60);
  doc.setFontSize(10);
  doc.text(order.supplier?.name || 'N/A', LEFT_MARGIN, 67);
  if (order.supplier?.address) doc.text(order.supplier.address, LEFT_MARGIN, 72);
  if (order.supplier?.phone) doc.text(order.supplier.phone, LEFT_MARGIN, 77);

  // Items Table
  // formatCurrency already produces clean ASCII spaces — no .replace() needed
  const tableData = order.items.map(item => [
    item.description,
    item.quantity.toString(),
    formatCurrency(item.unit_price),
    formatCurrency(item.total)
  ]);

  autoTable(doc, {
    startY: 85,
    margin: { left: LEFT_MARGIN, right: 15 },
    head: [[t('description'), t('quantity'), t('unit_price'), t('total')]],
    body: tableData,
    headStyles: { fillColor: [0, 31, 63] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: {
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' }
    },
    styles: { cellPadding: 3, fontSize: 10 }
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // Totals block — right-aligned, consistent with table
  doc.setFontSize(10);
  doc.setTextColor(0);
  const totalsLabelX = pageWidth - 55;
  const totalsValueX = pageWidth - 14;

  doc.text(`${t('total_amount')}:`, totalsLabelX, finalY, { align: 'right' });
  doc.text(formatCurrency(order.total_amount), totalsValueX, finalY, { align: 'right' });

  doc.text(`${t('paid_amount')}:`, totalsLabelX, finalY + 8, { align: 'right' });
  doc.text(formatCurrency(order.paid_amount), totalsValueX, finalY + 8, { align: 'right' });

  doc.setFont('helvetica', 'bold');
  doc.setDrawColor(0, 31, 63);
  doc.line(totalsLabelX - 30, finalY + 11, totalsValueX, finalY + 11); // separator line
  doc.text(`${t('balance')}:`, totalsLabelX, finalY + 17, { align: 'right' });
  doc.text(formatCurrency(order.balance), totalsValueX, finalY + 17, { align: 'right' });

  // Amount in words
  const wordsY = finalY + 30;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(0);
  const lang = i18n.language === 'fr' ? 'fr' : 'en';
  const amountInWords = numberToWords(Math.round(order.total_amount), lang);
  const fullText = lang === 'fr' 
    ? `Arrêtée la présente commande à la somme de : ${amountInWords}`
    : `The total amount of this order is set at: ${amountInWords}`;
  
  // Split text if too long
  const splitTitle = doc.splitTextToSize(fullText, pageWidth - LEFT_MARGIN - 15);
  doc.text(splitTitle, LEFT_MARGIN, wordsY);

  // Signature section
  const sigY = finalY + 45;
  doc.setFont('helvetica', 'normal');
  doc.setDrawColor(0);
  doc.line(LEFT_MARGIN, sigY, LEFT_MARGIN + 60, sigY);
  doc.text(t('approved_by'), LEFT_MARGIN, sigY + 5);

  doc.line(pageWidth - 75, sigY, pageWidth - 15, sigY);
  doc.text(t('received_by'), pageWidth - 75, sigY + 5);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Benna Stock Manager', pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });

  doc.save(`PO_${order.id.substring(0, 8)}.pdf`);
};
