import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from './currency';

interface OrderItem {
  description: string;
  quantity: number;
  unit_price: number;
  total: number;
}

interface OrderData {
  id: string;
  order_date: string;
  supplier: {
    name: string;
    address?: string;
    phone?: string;
    email?: string;
  } | null;
  items: OrderItem[];
  total_amount: number;
  paid_amount: number;
  balance: number;
}

interface Settings {
  company_logo?: string;
}

export const generateOrderPDF = (order: OrderData, settings: Settings, t: (key: string) => string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // Add Logo
  if (settings.company_logo) {
    try {
      doc.addImage(settings.company_logo, 'PNG', 15, 15, 30, 30);
    } catch (e) {
      console.error('Error adding logo to PDF:', e);
    }
  }

  // Header Info
  doc.setFontSize(20);
  doc.setTextColor(0, 31, 63); // Navy Blue (#001f3f)
  doc.text(t('purchase_order'), pageWidth - 15, 25, { align: 'right' });

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`${t('order_number')}: ${order.id.substring(0, 8)}`, pageWidth - 15, 32, { align: 'right' });
  doc.text(`${t('order_date')}: ${new Date(order.order_date).toLocaleDateString()}`, pageWidth - 15, 37, { align: 'right' });

  // Supplier Info
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(t('supplier'), 15, 60);
  doc.setFontSize(10);
  doc.text(order.supplier?.name || 'N/A', 15, 67);
  if (order.supplier?.address) doc.text(order.supplier.address, 15, 72);
  if (order.supplier?.phone) doc.text(order.supplier.phone, 15, 77);

  // Table
  const tableData = order.items.map(item => [
    item.description,
    item.quantity.toString(),
    formatCurrency(item.unit_price).replace(/\u00A0/g, ' '),
    formatCurrency(item.total).replace(/\u00A0/g, ' ')
  ]);

  autoTable(doc, {
    startY: 85,
    head: [[t('description'), t('quantity'), t('unit_price'), t('total')]],
    body: tableData,
    headStyles: { fillColor: [0, 31, 63] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: {
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' }
    },
    styles: { cellPadding: 2, fontSize: 10 }
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // Totals
  doc.setFontSize(10);
  const totalsLabelX = pageWidth - 45;
  const totalsValueX = pageWidth - 14;
  
  doc.text(`${t('total_amount')}:`, totalsLabelX, finalY, { align: 'right' });
  doc.text(formatCurrency(order.total_amount).replace(/\u00A0/g, ' '), totalsValueX, finalY, { align: 'right' });
  
  doc.text(`${t('paid_amount')}:`, totalsLabelX, finalY + 7, { align: 'right' });
  doc.text(formatCurrency(order.paid_amount).replace(/\u00A0/g, ' '), totalsValueX, finalY + 7, { align: 'right' });
  
  doc.setFont('helvetica', 'bold');
  doc.text(`${t('balance')}:`, totalsLabelX, finalY + 14, { align: 'right' });
  doc.text(formatCurrency(order.balance).replace(/\u00A0/g, ' '), totalsValueX, finalY + 14, { align: 'right' });

  // Signatures
  const sigY = finalY + 40;
  doc.setFont('helvetica', 'normal');
  doc.line(15, sigY, 75, sigY);
  doc.text(t('approved_by'), 15, sigY + 5);

  doc.line(pageWidth - 75, sigY, pageWidth - 15, sigY);
  doc.text(t('received_by'), pageWidth - 75, sigY + 5);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Benna Stock Manager', pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });

  // Open PDF
  doc.save(`PO_${order.id.substring(0, 8)}.pdf`);
};
